### PR TITLE
Added CareChain logo

### PR DESCRIPTION
**Pull request by advatar**
Please add our logo in the following sections 

- Healthcare Data Infrastructure
- Electronic and Patient Health Records
- Identity

Find out more about us here https://www.carechain.io and here https://www.carechain.io/wp.pdf

### CODE REVIEW

**Comment by acoravos** [comment]
@advatar -- for simplicity, we are only adding the logo to one box. Lots of projects generally have multiple features. You can include these in the text write up. What box would you say your dominant work is in? In this case, we often put a project in "Healthcare Data Infrastructure"

**Comment by acoravos** [comment]
For reference -- HashedHealth is in a few boxes because they are a consulting/dev shop that's working on multiple projects. Are you shipping multiple projects? Also, saw your repo and looks like your identity project is based off UPort or is it a different identity product?

**Comment by acoravos** [comment]
Also when you submit the pull request, please update the README, too like this example: https://github.com/acoravos/healthcare-blockchains/pull/21

**Comment by advatar** [comment]
Correct, we are using uport and infrastructure will do fine

**Comment by advatar** [comment]
I added a section to the table in README.md

**Comment by acoravos** [comment]
Great -- thanks @advatar. Merging it in.

**Pull request merged**
