### PR TITLE
Added lympo.io

### PR DESCRIPTION
**Pull request by eveningcoder**
Adding lympo.io to Electronic and Patient Health Records

### CODE REVIEW

**Comment by pfletcherhill** [comment]
Thanks for this, @eveningcoder. Do you mind re-writing the blurb about Lymph in the third-person just to be consistent?

**Comment by eveningcoder** [comment]
Thank you @pfletcherhill for suggestion, I changed the info text, anything else?

**Comment by eveningcoder** [comment]
Any updates on the request :)?

**Comment by pfletcherhill** [comment]
Great, thanks for making the update, @eveningcoder!

**Pull request merged**
